# Generated by Django 6.0.3 on 2026-04-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_manager_email'),
        ('finance', '0002_dailyplsnapshot_revenue_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplsnapshot',
            options={'ordering': ['-snapshot_date'], 'verbose_name': 'Daily P&L snapshot'},
        ),
        migrations.RenameField(
            model_name='dailyplsnapshot',
            old_name='date',
            new_name='snapshot_date',
        ),
        migrations.AlterUniqueTogether(
            name='dailyplsnapshot',
            unique_together={('branch', 'snapshot_date')},
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='gross_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='manual_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='manual_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='net_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='net_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='sales_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='supplier_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyplsnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='dailyplsnapshot',
            index=models.Index(fields=['-snapshot_date'], name='finance_dai_snapsho_4ef38a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplsnapshot',
            index=models.Index(fields=['branch', '-snapshot_date'], name='finance_dai_branch__1b2098_idx'),
        ),
    ]
