# Generated by Django 6.0.3 on 2026-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager_email',
            field=models.EmailField(blank=True, help_text='Email for low stock alerts', max_length=254),
        ),
    ]
