# Generated by Django 6.0.3 on 2026-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_user_options_alter_user_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, help_text='Short unique branch code used for sequences', max_length=20, null=True, unique=True),
        ),
    ]
