# Generated by Django 6.0.3 on 2026-05-16 16:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_alter_user_options_alter_user_branch_and_more'),
        ('finance', '0004_account_accountingperiod_journalentry_journalline_and_more'),
        ('orders', '0007_ordernumbersequence_payment_idempotency_key_and_more'),
        ('products', '0004_remove_productvariant_products_pr_sku_dcab68_idx_and_more'),
        ('suppliers', '0002_purchasepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('manual', 'Manual')], max_length=20)),
                ('snapshot_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_products', models.PositiveIntegerField()),
                ('total_variants', models.PositiveIntegerField()),
                ('total_units', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_stock_count', models.PositiveIntegerField()),
                ('out_of_stock_count', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.PositiveIntegerField()),
                ('physical_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_quantity', models.IntegerField(blank=True, null=True)),
                ('variance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorysnapshot')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('sale', 'Sale'), ('adjustment', 'Stock Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Customer Return'), ('damage', 'Damage Write-off'), ('count', 'Physical Count'), ('reservation', 'Stock Reservation'), ('reservation_release', 'Reservation Release')], max_length=20)),
                ('transaction_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('quantity_change', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='branches.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('general_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='finance.journalentry')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.purchase')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('account_type', models.CharField(choices=[('inventory_asset', 'Inventory Asset'), ('cogs_expense', 'Cost of Goods Sold'), ('inventory_adjustment', 'Inventory Adjustment'), ('purchase_price_variance', 'Purchase Price Variance'), ('sales_revenue', 'Sales Revenue'), ('sales_discount', 'Sales Discount')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_ledger_entries', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.inventorytransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cost_layers', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='products.productvariant')),
                ('source_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.inventorytransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransactionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('next_number', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('physical_count', 'Physical Count'), ('damage', 'Damage/Loss'), ('theft', 'Theft'), ('correction', 'Data Correction'), ('transfer', 'Branch Transfer'), ('return_to_supplier', 'Return to Supplier')], max_length=20)),
                ('adjustment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('system_quantity', models.PositiveIntegerField(help_text='Current system stock level')),
                ('actual_quantity', models.PositiveIntegerField(help_text='Actual counted/physical quantity')),
                ('adjustment_quantity', models.IntegerField(help_text='Adjustment amount (actual - system)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_value_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.TextField(help_text='Detailed reason for adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='branches.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='products.product')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.purchase')),
                ('transfer_to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_stock_adjustments', to='branches.branch')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockadjustment'),
        ),
        migrations.CreateModel(
            name='StockAdjustmentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('next_number', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['branch', 'snapshot_date'], name='inventory_i_branch__3b6f72_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['snapshot_type', 'snapshot_date'], name='inventory_i_snapsho_43bf0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysnapshot',
            unique_together={('branch', 'snapshot_type', 'snapshot_date')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorysnapshotitem',
            unique_together={('snapshot', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_i_branch__e6d95b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['account_type', 'created_at'], name='inventory_i_account_e174cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['transaction'], name='inventory_i_transac_cf2cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['branch', 'product', 'variant', 'created_at'], name='inventory_i_branch__db3728_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorytransactionsequence',
            unique_together={('branch', 'date')},
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['branch', 'status'], name='inventory_s_branch__5d7bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjustment_type', 'status'], name='inventory_s_adjustm_6f95e4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjustment_number'], name='inventory_s_adjustm_1d7aec_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_i_branch__9f9416_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'variant', 'created_at'], name='inventory_i_product_a4a74f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='inventory_i_transac_986cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_number'], name='inventory_i_transac_3bd512_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='non_zero_quantity_change'),
        ),
        migrations.AlterUniqueTogether(
            name='stockadjustmentsequence',
            unique_together={('branch', 'date')},
        ),
    ]
