# Generated by Django 6.0.3 on 2026-04-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_by_order_deposit_amount_and_more'),
        ('products', '0003_customizationservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='products.customizationservice'),
        ),
    ]
