# Generated by Django 6.0.3 on 2026-04-14 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_manager_email'),
        ('customers', '0001_initial'),
        ('orders', '0005_order_indexes'),
        ('products', '0004_remove_productvariant_products_pr_sku_dcab68_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_branch_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_branch_paystatus_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_payment_bc131d_idx',
            old_name='orders_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_transac_efd231_idx',
            old_name='orders_transaction_type_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='guest_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='orderidempotencyrecord',
            index=models.Index(fields=['endpoint', 'key', 'method'], name='orders_orde_endpoin_8dcbe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderidempotencyrecord',
            unique_together={('endpoint', 'key', 'method')},
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.order'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['active'], name='orders_stoc_active_0b9707_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at'], name='orders_stoc_expires_f55a9e_idx'),
        ),
    ]
