# Generated by Django 6.0.3 on 2026-05-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_user_options_alter_user_branch_and_more'),
        ('finance', '0004_account_accountingperiod_journalentry_journalline_and_more'),
        ('orders', '0006_orderidempotencyrecord_stockreservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='branches.branch')),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_order_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('adjustment', 'Adjustment')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('deposit', 'Deposit'), ('overpayment', 'Overpayment Credit'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('writeoff', 'Write Off')], default='payment', max_length=20),
        ),
    ]
