# Generated by Django 6.0.3 on 2026-04-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customizationservice'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_sku_dcab68_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_product_cee51f_idx',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase cost price for COGS calculation', max_digits=10),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='updated_at',
        ),
    ]
